name: Build

on:
  push:

jobs:
  build:
    name: Check if Build Passing
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Compile XeLaTeX document
        uses: xu-cheng/latex-action@1.2.0
        with:
          root_file: main.tex
          args: -pdf -xelatex -file-line-error -interaction=nonstopmode

      - name: Rename PDF
        run: mv main.pdf BP_Jan_Bittner.pdf

      - name: Upload Data
        uses: actions/upload-artifact@master
        with:
          name: bp-pdf
          path: BP_Jan_Bittner.pdf
