name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Compile XeLaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          args: -pdf -xelatex -file-line-error -interaction=nonstopmode
